### ISSUE TITLE
Deleting a file on filepicker with security policies

### ISSUE THREAD

**Issue by denodster** [filestack/filestack-rails#124]
If I want to delete a file on filepicker (because the associated model was destroyed) how would I do it? I don't see any method in the gem for such functionality....  I know I can use curl or something but that just feels dirty, I would much rather call whatever method this gem has for this purpose. Can someone help me out here?

**Comment by maurogeorge** [comment]
Hi @denodster ,

today the gem is only a thin wrapper around the JavaScript API.

A PR is welcome to add this feature.

Thanks

**Comment by staturecrane** [comment]
@denodster This is an old issue, but I want to comment nonetheless. The Rails gem is being remade to work with our new web SDK, including our Picker v3, meaning that you will have access to all associated features. 

We also have just released a revamped [Ruby SDK](https://github.com/filestack/filestack-ruby), which you can integrate into your Rails application and has all the features of our REST API, including delete, overwrite, image transformations, metadata, and so forth.
