### ISSUE TITLE
Support the new compress option

### ISSUE THREAD

**Issue by dylanfisher** [filestack/filestack-rails#134]
https://www.filepicker.com/documentation/file-processing/image-conversion/compress

This option can be very important because otherwise metadata isn't stripped out. For example, our client is uploading images that all have 3mb of metadata (a color profile) which otherwise isn't stripped out, even if the image is small. Consequently all jpg's are 3mb minimum filesize regardless of the image size and quality.

**Comment by maurogeorge** [comment]
You are right, this is not a valid option, feel free to send a PR to add this behavior.

More info about [contributing here](https://github.com/Ink/filepicker-rails/blob/master/CONTRIBUTING.md).

Thanks for the report @dylanfisher

**Comment by tbhockey** [comment]
Was this ever implemented? I don't seem to see any support for the new `compression` option. https://www.filestack.com/docs/image-transformations/compress

**Comment by ovelar** [comment]
@tbhockey I implemented a quick fix in PR #152 if you still need it.

**Comment by tbhockey** [comment]
Thanks m8. We ended up just building out the URL manually since we also needed to specify a specific compression amount.

**Comment by staturecrane** [comment]
@dylanfisher Plugin has been updated and all image transformations are now supported.
