### ISSUE TITLE
This action has been secured by the developer of this website. Error: The signature has expired

### ISSUE THREAD

**Issue by anu-vaid** [filestack/filestack-rails#135]
Some of our users in production are not getting the screen for uploading photos. The screen they get says 

_[uuid=23D9DF2AC704498D] This action has been secured by the developer of this website. Error: The signature has expired_

How can we resolve this?

**Comment by maurogeorge** [comment]
Hi,

I have some doubts:

- Do you are using [turbolinks](https://github.com/Ink/filepicker-rails/issues/52)?
- It is a reproducible problem? 
- Do you are using the latest release?
- We have a similar issue here https://github.com/Ink/filepicker-rails/issues/108
- You are using Policy?

Thanks for the report

**Comment by anu-vaid** [comment]
Hi Mauro,

It is not a reproducible error. We have a 1000+ users who post pictures and only a few have reported this problem but we need to solve it for them. (see attached)

Here’s the coffee script and policy signatures for file picker

$(document).ready ->
  $('.container').on 'click', '.btn-filepicker.feed-filepicker', (event) ->
    filepicker.setKey('AOyjuUbfRLu2SKti677Z1z')

    filepicker.pickAndStore
      multiple: true
      maxFiles: 50
      maxSize: 100*1024*1024
      services: [
        "COMPUTER"
        "DROPBOX"
        "GOOGLE_DRIVE"
      ]
      policy: $('.btn-filepicker').attr('policy')
      signature: $('.btn-filepicker').attr('signature')
    ,
      location: 'S3'
      path: '/feeds/'
    ,
      (InkBlobs) ->
        a = $(tmpl("template-feed-display", InkBlobs))
        $('#filepicker-files').append(a)
        return


  def filepicker_policy
    json_policy = {call: ['pick','store','read'], expiry: (Time.zone.now + 1.hour).to_i}.to_json
    Base64.urlsafe_encode64(json_policy)
  end

  def filepicker_signature
    OpenSSL::HMAC.hexdigest('sha256', CONFIG[:filepicker_app_secret], filepicker_policy)
  end



----
Anupama Vaid
www.parentsquare.com
805.637.8381
Santa Barbara, CA

**Comment by maurogeorge** [comment]
Hi @anu-vaid actually the gem is a simple wrapper and helpers around the Filepicker. If you belive this problem is related with the Filepicker internals I recommend you to contact the support directly.

**Comment by maurogeorge** [comment]
@anu-vaid other thing, at the moment the Policy class is private, we have a PR in progress to make this class public https://github.com/Ink/filepicker-rails/pull/133.

If you prefer to use this Policy class to generate the policies you can do something like this https://github.com/Ink/filepicker-rails/issues/112#issuecomment-69584387

I really don't know if this will fix you problem, but this way you are using the same policy generator that other users are using.

I hope thats helps you.

**Comment by AmaelColas** [comment]
Hi anu-vaid,
I kown it's a long time ago, but have you found the error ? We had the same issue on some files in production too , but we couln't reproduce the bug by ourselves ...?
