### ISSUE TITLE
Custom Text Dialog

### ISSUE THREAD

**Issue by vesuvius** [filestack/filestack-rails#139]
Hello Mauro,

I use your filepicker-rails gem in one of my projects and Andrew from Filepicker advised to ask you for some help.

Please visit this URL: https://www.filepicker.com/documentation/file-ingestion/javascript-api/pick?v=v2 and scroll down to the “Custom Dialog Text” section.
There is a param called customText.

I'm trying to pass this param (please see the last line in the “data” hash in my code bellow), but no success:

<%= f.filepicker_field :file_urls,
    data: {
        fp_store_location: "s3",
        fp_mimetypes: "image/*,application/pdf",
        fp_multiple: "true",
        fp_container: "modal",
        fp_maxfiles: installation_max_files - @installation_file_urls.count,
        fp_maxsize: "10485760",
        fp_image_quality: "50",
        fp_services: "WEBCAM,COMPUTER,GOOGLE_DRIVE",
        fp_button_text: "Add Files",
        fp_button_class: (btn_class rescue "fp__btn"),
        fp_custom_text: “Some_URL_Here"
    }
%>

All other fp_ params work pretty well.
What I’m doing wrong?

Best Regards,
Ivo

**Comment by maurogeorge** [comment]
Hi @vesuvius as you can see on the [readme](https://github.com/Ink/filepicker-rails#adding-an-upload-field-to-your-form) and [docs](http://www.rubydoc.info/github/Ink/filepicker-rails/master/FilepickerRails/FormHelper:filepicker_field) you don't need to pass the data attributes directly, you can do something like:

```ruby
<%= f.filepicker_field :file_urls, store_location: 's3' %>
```

The link to the docs you send is to the JavaScript, the gem is a wrapper around the widget, take a look on the docs of the [widget here](https://www.filepicker.com/documentation/file-ingestion/widgets/pick?v=v2).

Hope that help you.

**Comment by krystiangw** [comment]
Hi @maurogeorge 
The issue reason was lack of ```data-fp-custom-text``` attribute for pick widget. It was added [in the last filepicker-js library release](https://github.com/filepicker/filepicker-js/blob/2.2.1/src/widgets/widgets.js#L71).
However looks like it still doesn't work with filepicker-rails. I believe ```data-fp-custom-text``` attribute needs to be included [here](https://github.com/Ink/filepicker-rails/blob/master/lib/filepicker_rails/tag.rb#L5)

**Comment by maurogeorge** [comment]
@krystiangw you are right the docs are now updated and include the `data-fp-custom-text`. I will keep this open, this way anyone can make a PR to add this behavior.

**Comment by vesuvius** [comment]
Thank you very much!
What should I do from here?
Should I update the gem or something?

Regards,
Ivo

**Comment by maurogeorge** [comment]
@vesuvius you can pass this directly using the data attribute as you are doing. Or if you want to contribute to the gem and add this as a behavior you can follow [the instructions here](https://github.com/Ink/filepicker-rails/blob/master/CONTRIBUTING.md)

**Comment by vesuvius** [comment]
OK, I believe we have a kind of breakthrough.
Now I can see the changes in the dialog window, but only on my mobile devices — iPhone and iPad.
Unfortunately, no effect on desktop browsers — I tried with Safari, Chrome and Mozilla.

Best Regards,
Ivo

**Comment by maurogeorge** [comment]
@vesuvius I don't think this is a bug with the gem, since the gem is a thin wrapper to generate the widget only.

I think you can try this on a clean app to check this behavior, try without the gem too on a clean app. This way you can check if this is related or not with the code of your application.

**Comment by vesuvius** [comment]
Everything works fine now.
Thank you!
