### ISSUE TITLE
Support the new process.filepicker.com transformations

### ISSUE THREAD

**Issue by danmichaelson** [filestack/filestack-rails#140]
Such as converting an external URL on the fly, doing URL screenshots, etc.

https://www.filepicker.com/docs/image-transformations/v2/image-transformations

**Comment by staturecrane** [comment]
@danmichaelson We are currently in the process of revamping the Gem and these will be a part of our new image tag fields.

**Comment by staturecrane** [comment]
@danmichaelson The new version of the plugin is released, as well as our [Ruby SDK](https://github.com/filestack/filestack-ruby), both of which provide access to all of our image transformations. Please look to the README of this repository for more information.
