### ISSUE TITLE
Hide all filepicker url 

### ISSUE THREAD

**Issue by jlerpscher** [filestack/filestack-rails#142]
Hi,

For our customers with very strict policies, we need to replace all the filepicker urls by our domain.

I have set up CDN with cloudfront as described in documentation and I can now use `http://cdn.mydomain.com/api/file/an_awesome_key`.

We use filepicker for multiple formats, like pdf, images, office documents and I can't find any method other than `filepicker_image_url` to get the file url with cdn domain. Is there an other way? I think this method is not well named for our purpose.

Also, is it possible to hide the dialog url, `dialog.filepicker.io` (we have a plan with White Labeling)?

Many thanks

**Comment by maurogeorge** [comment]
Hi @jlerpscher, I think the only method to get the url of a file is `filepicker_image_url` probably this name was created in a old time when only images are handled.

About hiding the `dialog.filepicker.io` I recommend you take a look at the Filepicker docs and/or reach the support.

Thanks

**Comment by staturecrane** [comment]
@jlerpscher We have upgraded this plugin (and are now actively maintaining it). All returned URLs now come from CDN by default. Please let us know if we can help in any other way.
