### ISSUE TITLE
Configure Bucket name based on Environment and branch

### ISSUE THREAD

**Issue by chrisyeung1121** [filestack/filestack-rails#147]
I have a rails application which I have been using paperclip with. I realise that for each Filestack application, it is only binded to one s3 bucket, and I cannot set the bucket name based on the environment name I have.

I will have bucket name based on 1) MacAddress of dev machine, 2) git branch name, 3) Rails.env

So I will have bucket that is something like `companyname_development_2f8def9c_master`. I think it will be overkill to create an application for each right? especially it needs to be upgraded to a paid plan to connect to s3. 

Am I mistaken or is it currently the case?

**Comment by chrisyeung1121** [comment]
any updates?

**Comment by chrisyeung1121** [comment]
if there is support i will convert to filepicker

**Comment by staturecrane** [comment]
@chrisyeung1121 We have released a new version of this plugin and are now actively maintaining it. If you still need support with bucket support, please send an email to support@filestack.com and they will be able to assist you.
