### ISSUE TITLE
Access the generated policy and signature?

### ISSUE THREAD

**Issue by Deekor** [filestack/filestack-rails#148]
Is there a way to access the generated `policy` and `signature`? Our users will be uploading many file types where the `filepicker_image_tag` wont be appropriate and I need to append the `policy` and `singature` to the `filepicker_url` so our users can access the documents via the link.

**Comment by Deekor** [comment]
https://github.com/Ink/filepicker-rails/issues/112#issuecomment-69584387 this comment helped me.

**Comment by staturecrane** [comment]
@Deekor  We are revamping this gem and the signature and policy will be publicly available for you to access as you please.
