### ISSUE TITLE
cropDim doensn't work when uploading image

### ISSUE THREAD

**Issue by ChunAllen** [filestack/filestack-rails#149]
I want to resize for image when it's being displayed.

But I want it to have a crop size, when you're about to upload an image 
like this: 

<img width="1149" alt="screenshot 2016-08-17 16 28 05" src="https://cloud.githubusercontent.com/assets/2100728/17729628/aed151d6-6497-11e6-826d-753fb31ff5cd.png">

My current code is, 

```
            = f.filepicker_field :image_url,
              button_text: 'Click to upload your company picture',
              button_class: 'btn btn-default btn-block',
              onchange: 'onCompanyPhotoUpload(event)',
              cropDim: [250, 250]
```

but it's not working.

**Comment by amione** [comment]
Hi @ChunAllen ,
I recently helped one of our customers to get this working.

In https://github.com/Ink/filepicker-rails/blob/master/lib/filepicker_rails/tag.rb

You can add:

`:crop_dim`

To the dasherize section:

    FILEPICKER_OPTIONS_TO_DASHERIZE = [:button_text, :button_class, :mimetypes,
                                   :extensions, :container, :services,
                                   :drag_text, :drag_class, :store_path,
                                   :store_location, :store_access,
                                   :store_container, :multiple]

Then in your code you can use this to set the cropDim:

`crop_dim: "250, 250"`

I believe this should work.
