### ISSUE TITLE
Re-bind new filepicker_fields?

### ISSUE THREAD

**Issue by tbhockey** [filestack/filestack-rails#151]
For our image uploading UI, in some cases we need to dynamically generate filepicker_fields that weren't on the page at load time. The problem is, clicking those new buttons does not trigger the filepicker dialog.

As of this moment I've been unable to determine why this is. My guess is that the new elements need to be re-bound to the filepicker js, but even if that is the case I'm unsure how to do that as, best as I can tell, that is handled by the gem and I don't appear to have direct access to it.

If anyone offer some clarification or help on this I'd appreciate it. Thanks.

**Comment by staturecrane** [comment]
@tbhockey We are currently in the process of revamping this Gem to use our new File Picker, and one of the benefits will be that these kinds of dynamic field generations will be much simpler than the v2 iFrames.

**Comment by staturecrane** [comment]
@tbhockey We have revamped the plugin and released version 3.0.0. This integrates our new File Picker, and I believe this will help with your problem of dynamic field generation. Please look through the Readme and migration guide before upgrading. I am going to close this issue as we are not going to continue actively supporting the old version, but feel free to open it again if you have similar problems with new release.

**Comment by tbhockey** [comment]
Thank you for the update @staturecrane
