### ISSUE TITLE
Rails 5: undefined method `helper' for ActionController::API:Class

### ISSUE THREAD

**Issue by Deekor** [filestack/filestack-rails#153]
Just upgraded to Rails 5 and am now getting this error when starting my server.

    Rails 5: undefined method `helper' for ActionController::API:Class

Stack trace shows it's coming from

    filepicker-rails-2.1.0/lib/filepicker_rails/engine.rb:13:in `block (2 levels) in <class:Engine>': undefined method `helper' for ActionController::API:Class (NoMethodError)

**Comment by kyuss** [comment]
Merged and fixed in version 2.2.0.
