### ISSUE TITLE
undefined method `filepicker_rails`

### ISSUE THREAD

**Issue by vsrboth** [filestack/filestack-rails#159]
I am currently trying to use the `filestack_rails` v 2.2.0 and I get this problem whenever I start the server

```
method_missing': undefined method `filepicker_rails' for #<Rails::Application::Configuration:0x007ffd74a04280>
```

Don't quite get how the issue appears, but seems like the engines is not connected to my rails application.

**Comment by kyuss** [comment]
@vsrboth Can you please try:

`gem 'filestack-rails', require: 'filepicker-rails'`

I have changed gem name, but code remained the same until we have Picker V3 implemented with new API.

**Comment by vsrboth** [comment]
@kyuss thank you. It works now, but wait.. the current latest version hasn't implemented V3 yet?

**Comment by kyuss** [comment]
@vsrboth Not yet. That is planned for version 3.0.0 of this gem in the next couple weeks.

**Comment by vsrboth** [comment]
@kyuss thank you so much. I'll be waiting for that. In the mean time, I'll be using everything from the js first.

**Comment by aakashbarot** [comment]
I was using Filepicker rails and trying to upgrade to Filestack-rails and I am getting this error:

`/Users/aakasot/.rvm/gems/ruby-2.3.0@global/gems/railties-4.2.4/lib/rails/railtie/configuration.rb:95:in `method_missing': undefined method `filestack_rails' for #<Rails::Application::Configuration:0x007f8a439e5de8> (NoMethodError)`

My Gem list shows this two installed: 

```
filestack (2.1.0, 2.0.1)
filestack-rails (2.2.0)

```

Here is my line in application.rb 
`config.filestack_rails.api_key = "api_key"`

Please help.

**Comment by RemarkVisions** [comment]
I'm getting the same issue except I'm using the latest version of filestack-rails. There are also many conflicts with the filestack-rails dependencies conflicting with other gem dependencies like mimemagic which is popular with the soon-to-be-deprecated paperclip gem.

**Comment by anthonyto** [comment]
Solution for @aakashbarot's issue here https://github.com/filestack/filestack-rails/issues/181
