### ISSUE TITLE
January security updates?

### ISSUE THREAD

**Issue by Deekor** [filestack/filestack-rails#162]
I received an email back in January discussing security updates. I assume those updates are now in this gem?

The Email:

<img width="631" alt="screen shot 2017-07-13 at 12 45 10 pm" src="https://user-images.githubusercontent.com/1904267/28182350-23a8b924-67c9-11e7-94b4-833d55435147.png">

**Comment by staturecrane** [comment]
@Deekor Thanks for the question. Our Rails gem is a thin wrapper over our picker and does not currently have many of the features of our full API, like deleting and overwriting files. However, all of these are available in our [Ruby SDK](https://github.com/filestack/filestack-ruby), which you can easily integrate into your Rails application.

**Comment by staturecrane** [comment]
@Deekor We have released 3.0.0 of the Rails plugin, which has security integrated. For details on security implementations and for any additional information regarding security and your account, please contact support at support@filestack.com
