### ISSUE TITLE
undefined method `table_name' for Client:Class

### ISSUE THREAD

**Issue by martinverdejo** [filestack/filestack-rails#168]
I recently tried to upgrade to filestack-rails 3.0. And now I am running into a model name error on rails.
```
> rails c
/Users/martin/.rvm/gems/ruby-2.3.1@rails-project-template/gems/apartment-1.2.0/lib/apartment/adapters/postgresql_adapter.rb:52:in `block in process_excluded_model': undefined method `table_name' for Client:Class (NoMethodError)
```
I read a bit on [filestack-ruby](https://github.com/filestack/filestack-ruby#usage) and learned that it uses `Client` as a constant, which is also an ApplicationRecord model name in my rails app.
I also read that you can configure your app to use a different client name but it looks like that option has purely to do with the JS side.
```
config.filestack_rails.client_name = "custom_client_name"
```
I'm not totally sure that this is the cause, and whether it's a real issue for filestack-rails.

**Comment by staturecrane** [comment]
@martinverdejo Hello, thanks for the comment. I think this ends up being an issue for both the Rails plugin and the SDK. You are right that the Client from the Ruby SDK is injected and the custom Client name is only for the Client-side File Picker. I will work to rename the Client on the Ruby SDK to something more specific, and then make any changes necessary in this plugin to facilitate that.

**Comment by staturecrane** [comment]
@martinverdejo I have gotten the go ahead to fix this issue. Expect an updated release very soon.

**Comment by staturecrane** [comment]
@martinverdejo New release (3.1.0) pulls in updated Ruby SDK with Client and Filelink classes changed to FilestackClient and FilestackFilelink. This should solve your namespace issue. Please update the Rails plugin and your problem should be resolved. I am closing for now, but feel free to reopen if you have any further issues.

**Comment by martinverdejo** [comment]
Thanks a lot! Will update my gems soon!
