### ISSUE TITLE
 undefined method `filepicker_rails'

### ISSUE THREAD

**Issue by mmohitcc** [filestack/filestack-rails#169]
I just update to version 3.0 of the gem, and i'm getting this error when I restart my server.  Running on ruby 2.4.0

![screen shot 2017-07-31 at 12 27 05 pm](https://user-images.githubusercontent.com/16858810/28792164-eb28cec8-75eb-11e7-8810-9010a2dc3ecd.png)

**Comment by staturecrane** [comment]
@mmohitcc Version 3.0.0 is a major, breaking change, including changing the namespace from FilepickerRails to FilestackRails. So the config.filepicker_rails parameter you are trying to access no longer exists; it has been replaced by config.filestack_rails. There is a migration guide in the [README](https://github.com/filestack/filestack-rails/blob/master/README.md), as well as all information you will need to successfully run the plugin.
