### ISSUE TITLE
cannot load such file -- filestack-rails (LoadError)

### ISSUE THREAD

**Issue by niclin** [filestack/filestack-rails#170]
version : Rails 5.0.4

As per document, my project get load error when gem file add `gem 'filestack-rails', require: 'filestack-rails'`

<img width="1161" alt="2017-08-03 1 41 03" src="https://user-images.githubusercontent.com/7571949/28907570-6dd79004-7851-11e7-9f9a-3840ec6e52df.png">

after change to `gem "filestack-rails", require: "filepicker-rails"` can be work for me!!

but I still can't use `<%= filestack_js_include_tag %>` in layout.

<img width="818" alt="2017-08-03 1 41 47" src="https://user-images.githubusercontent.com/7571949/28907592-8b5970fc-7851-11e7-8d1c-e7d38164d56b.png">

the error message tell me `Did you mean?  filepicker_js_include_tag`

so I can not use it helper

Finally, I still use `<script src="https://static.filestackapi.com/v3/filestack-0.6.2.js"></script>` solution

**Comment by staturecrane** [comment]
@niclin Please run "bundle update" as your bundler is still installing the previous version of the Rails plugin, which is where your errors are coming from. If you do that and then follow the instructions on the Readme, all should work for you :) 

Also, we are modifying the installation instructions. You no longer need to add the "require: "filestack-rails" clause to your Gemfile.
