### ISSUE TITLE
Security problem?

### ISSUE THREAD

**Issue by jpawlyn** [filestack/filestack-rails#174]
Hi. With security turned off the filepicker is working really well. The view code is as follows:
```
f.filestack_field :avatar_url, 'Upload an avatar', pickerOptions: { accept: ['.jpg', '.png'], maxSize: 262144, maxFiles: 1, imageDim: [200, 200], transformations: { crop: { aspectRatio: 1/1, force: true } } }
```

With security turned on, I've added `config.filestack_rails.security = {}` together with a value for `config.filestack_rails.app_secret` but when the filepicker opens, the call to `https://cloud.filestackapi.com/folder/list` returns a 401 unauthorized ({"error":"Invalid Policy","c":"c157269d-ec1a-4c6f-ad57-d8d1ba006475","i":"CLR-us-e-1-10","t":1508161246}). And when I select a file, a call to `https://upload.filestackapi.com/multipart/start` gives a 403 forbidden ({"error":"Invalid App policy","c":"f9ab6175-fc19-439c-9111-e0716f9de5ed","i":"UPL-eu-w-1-10","t":1508161263}). 

We are using ruby 2.4.1, rails 5.1.4 and version 3.1.0 of filestack-rails. If I've missed anything obvious then apologies! Thanks,

Jolyon

**Comment by staturecrane** [comment]
Hi @jpawlyn,

Security is not really intended to be used with an empty object. The Rails plugin will set a default expiry in that instance, but it is very short-lived and not intended to be used in production. I would suggest using a real policy, something like 
```
config.filestack_rails.security = {'expiry' => LONGER_EXPIRY, 'call' => %w[pick store read convert] }
```
If that does not solve your problem, please let me know and I will look into this further. 

Thanks!

**Comment by jpawlyn** [comment]
Apologies. Am working with a VM that doesn't update it's date time. As soon as I did that that, it worked. Apologies again.
