### ISSUE TITLE
Expiry length ignored?

### ISSUE THREAD

**Issue by taylorthurlow** [filestack/filestack-rails#175]
Hi, I'm on Rails `4.2.1`, Ruby `2.3.1`, and filestack-rails `3.1.0`. I'm setting up in `application.rb` as follows:

    config.filestack_rails.security = { 'expiry' => 4663446066,  'call' => %w[pick read stat write writeUrl store convert remove exif] }

As far as I can tell, this is exactly how to define your own expiry. According to [this epoch converter](https://www.epochconverter.com/), 4663446066 corresponds to 100 years from the current date. Despite this, the server is still using a one-hour expiry. This is evident in the fact that I can no longer delete files (all I'm using security for at the moment) after an hour, and also from a quick look at the policy it generates:

    2.3.1 :001 > Rails.application.config.filestack_rails.security.policy
     => "eyJleHBpcnkiOjE1MDg2NDIyNzYsImNhbGwiOlsicGljayIsInJlYWQiLCJzdGF0Iiwid3JpdGUiLCJ3cml0ZVVybCIsInN0b3JlIiwiY29udmVydCIsInJlbW92ZSIsImV4aWYiXX0="

Plugging this policy into the helper form on filestack's developer portal, tells me that this policy code represents: `{"expiry":1508641608,"call":["pick","read","stat","write","writeUrl","store","convert","remove","exif"]}`

Which is the expiry length for 1 hour. Am I doing something wrong?

* Edited to fix an incorrect version of the gem.

**Comment by staturecrane** [comment]
Hi @taylorthurlow. I will attempt to replicate and then get back to you.

**Comment by taylorthurlow** [comment]
Hi @staturecrane, any chance that you've been able to take a look at this? Sorry to bother.

**Comment by taylorthurlow** [comment]
Alright, I did some poking around the source and I found the source of the issue. It's a problem with the `filestack` gem, and I've opened [an issue there](https://github.com/filestack/filestack-ruby/issues/18) and will be submitting a pull request shortly.

**Comment by taylorthurlow** [comment]
This issue is caused by passing a hash with **string** keys and not **symbol** keys. The documentation in the readme uses string keys:

`config.filestack_rails.security = {'call' => %w[pick store read convert] }`

If you are to try and include an `'expiry'` key, it will be ignored. Use `:call` and `:expiry` instead.
