### ISSUE TITLE
How to save metadata to @user.filestack_url

### ISSUE THREAD

**Issue by masudhossain** [filestack/filestack-rails#176]
I'm currently doing 
`<%= f.filestack_field :filepicker_url, 'Upload Your Avatar!', id: 'unique-id' %> 
`to upload files and it's working fine. but I also want to save the metadata (such as name, filetype, ect.) to my rails application. Otherwise, i can't grab the name of the files for my users to see.

**Comment by staturecrane** [comment]
@masudhossain At the moment, the only parameter supported in the form_helper is the URL. The one-to-one nature of the form fields makes something like metadata tricky, and it's not really what the Rails app is designed for (it's just a small widget, really). 

We do have a [Ruby SDK](https://github.com/filestack/filestack-ruby), which is designed as a full-feature uploading solution, and includes all transformation and metadata calls, but this would only be useful in retrieving metadata after the file has been uploaded. You can also integrate our 
  [File Picker]( https://github.com/filestack/filestack-js) directly into your frontend, where you can access all the metadata at upload time.
