### ISSUE TITLE
Create/update images through ActiveAdmin form 

### ISSUE THREAD

**Issue by billkhan63** [filestack/filestack-rails#224]
I have bee looking since last 2 hours, but unfortunately not able to find any useful example or clue to integrate `filestack` with `active-admin`.Or even is it do-able or not.
I am using 
`gem "filestack-rails", "5.2.1"`
`gem "rails", "6.0.2.1"`
and `S3` for storage.
thanks in advance.

**Comment by gabifiolek** [comment]
Hi @billkhan63 :) 
I don't know exactly what you want to implement but have you tried to create a custom page?
You can create a partial with all filestack-js tags (HTML) and then use it:
  `content do
    render partial: 'your_partial'
  end`
Please take a look:
https://activeadmin.info/10-custom-pages.html

Let me know if that helps you.

**Comment by gabifiolek** [comment]
@billkhan63 I'll close the ticket, but if you still have some concerns, please reopen.
