### ISSUE TITLE
No Options passed to image tag w/o a transform

### ISSUE THREAD

**Issue by JoshReedSchramm** [filestack/filestack-rails#225]
In: https://github.com/filestack/filestack-rails/blob/4c672d67038b54136f198cfe72a43ee4391ce55e/app/helpers/filestack_rails/application_helper.rb#L38

If you pass standard html options (class for example) those options are not passed along to the image tag helper unless you also pass a transform. If you pass a transform it will pull out the transform option then pass along the rest of the tag options.

**Comment by gabifiolek** [comment]
Hello @JoshReedSchramm ! Thank you for letting us know.
I've already fixed the issue in `filestack-rails 5.2.2`.
Thanks!
