### ISSUE TITLE
Custom CNAME not used for Javascript script include

### ISSUE THREAD

**Issue by JoshReedSchramm** [filestack/filestack-rails#226]
In: https://github.com/filestack/filestack-rails/blob/4c672d67038b54136f198cfe72a43ee4391ce55e/lib/filestack_rails/filestack_js.rb#L9

If you provide a custom cname in the configuration that cname is ignored when including the javascript script tag. This is problematic if the purpose of setting a custom cname is to ensure that all traffic from filestack comes from a domain you control. (In our case we are doing this to avoid corporate firewall blocking of filestack.io, filestackcontent cdn, etc.)

**Comment by gabifiolek** [comment]
Hello @JoshReedSchramm ! Thank you for letting us know.
I've already fixed the issue in `filestack-rails 5.2.2`.
Thanks!
