### ISSUE TITLE
multiple upload support

### ISSUE THREAD

**Issue by zachlevy** [filestack/filestack-rails#229]
How can I upload multiple photos?

I'm using the `maxFiles` option which allows me to upload multiple files to filestack servers.

```ruby
<%= form.filestack_field :photos, 'Upload',  pickerOptions: { accept: ["image/*"], maxFiles: 6 } %>
```

I'm expecting uploading 2 photos to give me a url to grab both photos from.

```html
<input id="mymodel_photos" style="display:none" type="text" name="mymodel[photos]">
```

```javascript
$('#mymodel_photos').val();
```

returns a just the first file url like https://cdn.filestackcontent.com/IjTo4OxQvi7dwepWfjCH

inspecting params doesn't show any other fields.

```ruby
<ActionController::Parameters {
  "mymodel"=>{
    "photos"=>"https://cdn.filestackcontent.com/IjTo4OxQvi7dwepWfjCH",
  }, "commit"=>"Create Mymodel",
} permitted: false>
```

**Comment by gabifiolek** [comment]
@zachlevy Let me know what do you have setup in `application.rb` file:
`config.filestack_rails.version = "3.x.x"` 
It helps me to determine which version of filestack-js you use.

**Comment by gaaabiko** [comment]
@zachlevy Sorry for the delay. I've updated the library (5.4.0) and I've added a support for uploading multiple files. Now, you are able to grab all urls of uploaded files. Let me know if that works for you as you expected. If you need anything else, ping me.
