### ISSUE TITLE
The `get_policy_and_signature` method is confusing

### ISSUE THREAD

**Issue by phaedryx** [filestack/filestack-rails#233]
This method name https://github.com/filestack/filestack-rails/blob/0850f4e0a12d56bed8959e136cb241e993ea5082/app/helpers/filestack_rails/application_helper.rb#L76 makes it seem like you can do this in your view:
```
<% policy, signature = get_policy_and_signature %>
```
but the method returns `[signature, policy]` so that code is wrong. I would expect a method named `get_policy_and_signature` to return `[policy, signature]`

**Comment by gabifiolek** [comment]
@phaedryx Good point! Thanks for letting me know.

**Comment by gabifiolek** [comment]
@phaedryx Fixed.
