### ISSUE TITLE
Issue with Active Admin implementation

### ISSUE THREAD

**Issue by ChrisSki** [filestack/filestack-rails#55]
I'm not sure if this an issue with integration with Active Admin, Formtasitc (which is used by AA by default for forms) or with Rails 4, but I can't seem to get around it. 

```
form do |f|
f.inputs "Town" do
  f.input :town
  f.input :name
  f.filepicker_field :filepicker_url
end
f.actions
end
```

I get the following error on the page where I submit the form:

```
Showing /Users/***/.rvm/gems/ruby-2.0.0-p0@Guides/bundler/gems/active_admin-72a9c30cef47/app/views/active_admin/resource/edit.html.arb where line #1 raised:

Set config.filepicker_rails.api_key

Extracted source (around line #1):
1:  insert_tag renderer_for(:edit)
```

I have followed the instructions from the github docs and have my API key in config/application.rb. Has anyone else run into this error? I use Filepicker in another php app and love it, so I'd rather not have to use Paperclip for my Rails apps.

Here's a gist to the full trace
[Gist](https://gist.github.com/ChrisSki/6334879)

**Comment by jtoy** [comment]
any update on this?

**Comment by denodster** [comment]
this is still the case in 1.3.0

**Comment by nileshtrivedi** [comment]
Anybody using filepicker with activeadmin mind sharing the code?

```f.input``` generates both label tag and input field, whereas ```f.filepicker_field``` generates only the input field which breaks alignment.

**Comment by nileshtrivedi** [comment]
Never mind. I made it work as follows:

```
class FilepickerInput < Formtastic::Inputs::StringInput
	def input_html_options
		super.merge({:type => "filepicker", "data-fp-apikey".to_sym => "MY_API_KEY"})
	end
end
```

**Comment by geoffrey** [comment]
@nileshtrivedi how did you ended up adding the js include tags 
```
<%= filestack_js_include_tag %>
<%= filestack_js_init_tag %> 
```

from https://github.com/filestack/filestack-rails in activeadmin ?

**Comment by stevegrossi** [comment]
I'd love to know if you figured this out @geoffrey. I'm having the same difficulty: no access to ActiveAdmin's layout, and adding 

```erb
<%= filestack_js_include_tag %>
<%= filestack_js_init_tag %> 
```

to my `_form.html.erb` raises `undefined local variable or method 'filestack_js_include_tag'`
