### ISSUE TITLE
Support Store Container

### ISSUE THREAD

**Issue by travisp** [filestack/filestack-rails#77]
With the new Filepicker pricing changes, if you use image conversion, it's important to be able to use one API key for multiple environments. Ink has suggested that the way to do this is provide different containers and provides the data-fp-store-container option:

"The bucket or container in the specified file store where the file should end up. This is especially useful if you have different containers for testing and production and you want to use them both on the same filepicker app. If this parameter is omitted, the file is stored in the default container specified in your developer portal."

This can be added just with data: {fp_store_container: container-name}, but it would be nice to be supported directly within the field, or, better, as a global setting.

**Comment by danmichaelson** [comment]
Along with this feature, the default pick/store policy should specify the storage bucket (rather than allow storage to any bucket).
